package enums;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOT,
    FAILEDSTEPSSCREENSHOT,
    SKIPPEDSTEPSSCREENSHOT,
    RETRYFAILEDTESTS,
    RUNMODE,
    SENDRESULTSTOELK,
    BROWSER
}
